// try catch is used to handle sync code errors
// try {
//     let a = 12;
//     let b = 0;
//     res = a / b;
//     if (res == Infinity) {
//         throw Error("Invalid Inputs");
//     }
//     console.log(res);
// } catch (error) {
//     console.log(error);
    // console.log(error.name);
    // console.log(error.message);
// }
// console.log("Hello World");


// console.log(1);
// to implement ajax(json[{},{},{},{}])- we use fetch/axios

// .then and .catch is part of promise(using promise)
// .then() // data aa jae (successful)
// .catch() // data mein error (unsuccess)
// fetch("https://jsonplaceholder.typicode.com/todos/1")
//     .then((response) => response.json())
//     .then((json) => console.log(json))
//     .catch((error) => console.log(error));
// console.log(3);
